// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgIJxrMYNeMCAn4JBURxYdcxB1dUv7Ago',
    appId: '1:201159384368:web:44364e27519ed800563cf5',
    messagingSenderId: '201159384368',
    projectId: 'nestfinder-flutter',
    authDomain: 'nestfinder-flutter.firebaseapp.com',
    storageBucket: 'nestfinder-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQSjfwr7ghufqY6NOluM1MX_QG-oNw19o',
    appId: '1:201159384368:android:28be6df47ef9d988563cf5',
    messagingSenderId: '201159384368',
    projectId: 'nestfinder-flutter',
    storageBucket: 'nestfinder-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiVSp7ZrDV-yvzOgvoMAFomZDR4xsK_XE',
    appId: '1:201159384368:ios:c9afabfbe1989ba6563cf5',
    messagingSenderId: '201159384368',
    projectId: 'nestfinder-flutter',
    storageBucket: 'nestfinder-flutter.firebasestorage.app',
    iosBundleId: 'com.example.sharenoderentallatformHaiKhanh52026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiVSp7ZrDV-yvzOgvoMAFomZDR4xsK_XE',
    appId: '1:201159384368:ios:c9afabfbe1989ba6563cf5',
    messagingSenderId: '201159384368',
    projectId: 'nestfinder-flutter',
    storageBucket: 'nestfinder-flutter.firebasestorage.app',
    iosBundleId: 'com.example.sharenoderentallatformHaiKhanh52026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgIJxrMYNeMCAn4JBURxYdcxB1dUv7Ago',
    appId: '1:201159384368:web:d4828abd91461e77563cf5',
    messagingSenderId: '201159384368',
    projectId: 'nestfinder-flutter',
    authDomain: 'nestfinder-flutter.firebaseapp.com',
    storageBucket: 'nestfinder-flutter.firebasestorage.app',
  );
}
